services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    #restart: unless stopped
    ports:
      - "3000:3000"
  # Uncomment the following if you want to use a reverse proxy
  proxy:
    image: caddy:2-alpine
    #restart: unless-stopped
    links:
      - frontend
    hostname: testing.azcyouth.in
    ports: [
       "443:443",
       "80:80"
    ]
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy-data:/data
      - ./caddy/caddy-config:/config